// Auth Type
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const AUTH_LOADING = 'AUTH_LOADING';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const RESEND_EMAIL_SUCCESS = 'RESEND_EMAIL_SUCCESS';


