export const SUCCESS = 'SUCCESS';
export const ERROR = 'ERROR';
export const LOADING = "LOADING";

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const AUTH_LOADING = 'AUTH_LOADING';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGOUT_ACTION = "LOGOUT_ACTION";

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const RESEND_EMAIL_SUCCESS = 'RESEND_EMAIL_SUCCESS';

export const FORGOT_SUCCESS = 'FORGOT_SUCCESS';
export const FORGOT_ERROR = 'FORGOT_ERROR';

export const COMPLETE_PROFILE_SUCCESS = "COMPLETE_PROFILE_SUCCESS"
export const COMPLETE_PROFILE_ERROR = "COMPLETE_PROFILE_ERROR";

export const PROFILE_SUCCESS = "PROFILE_SUCCESS";
export const PROFILE_ERROR = "PROFILE_ERROR";

export const PROFILE_UPDATE_SUCCESS = "PROFILE_UPDATE_SUCCESS";
export const PROFILE_UPDATE_ERROR = "PROFILE_UPDATE_ERROR";

export const TRIAL_SUCCESS = "TRIAL_SUCCESS"
export const TRIAL_ERROR = "TRIAL_ERROR"

export const VIEW_TRIAL_SUCCESS = "VIEW_TRIAL_SUCCESS"
export const VIEW_TRIAL_ERROR = "VIEW_TRIAL_ERROR"

export const RECRUITING_STATUS_SUCCESS = "RECRUITING_STATUS_SUCCESS"
export const RECRUITING_STATUS_ERROR = "RECRUITING_STATUS_ERROR"

export const CREATE_TRIAL_SUCCESS = "CREATE_TRIAL_SUCCESS"
export const CREATE_TRIAL_ERROR = "CREATE_TRIAL_ERROR"

export const SPONSORE_LIST_SUCCESS = "SPONSORE_LIST_SUCCESS"
export const SPONSORE_LIST_ERROR = "SPONSORE_LIST_ERROR"

export const SPONSOR_DASHBOARD_SUCCESS = "SPONSOR_DASHBOARD_SUCCESS"
export const SPONSOR_DASHBOARD_ERROR = "SPONSOR_DASHBOARD_ERROR"

export const TRIAL_CLINIC_LIST_ERROR = "TRIAL_CLINIC_LIST_ERROR"
export const TRIAL_CLINIC_LIST_SUCCESS = "TRIAL_CLINIC_LIST_SUCCESS"

export const TRIAL_CLINIC_DETAIL_SUCCESS = "TRIAL_CLINIC_DETAIL_SUCCESS"
export const TRIAL_CLINIC_DETAIL_ERROR = "TRIAL_CLINIC_DETAIL_ERROR";

export const NEW_TRIAL_REQUEST_SUCCESS = "NEW_TRIAL_REQUEST_SUCCESS"
export const NEW_TRIAL_REQUEST_ERROR = "NEW_TRIAL_REQUEST_ERROR";

export const NEW_TRIAL_REQUEST_DETAIL_SUCCESS = "NEW_TRIAL_REQUEST_DETAIL_SUCCESS"
export const NEW_TRIAL_REQUEST_DETAIL_ERROR = "NEW_TRIAL_REQUEST_DETAIL_ERROR"

export const NEW_TRIAL_REQUEST_STATUS_UPDATE_SUCCESS = "NEW_TRIAL_REQUEST_STATUS_UPDATE_SUCCESS"
export const NEW_TRIAL_REQUEST_STATUS_UPDATE_ERROR = "NEW_TRIAL_REQUEST_STATUS_UPDATE_ERROR"

export const SPONSORE_DETAIL_SUCCESS = "SPONSORE_DETAIL_SUCCESS";
export const SPONSORE_DETAIL_ERROR = "SPONSORE_DETAIL_ERROR";

export const SPONSORE_APPLY_TRIAL_SUCCESS = "SPONSORE_APPLY_TRIAL_SUCCESS"
export const SPONSORE_APPLY_TRIAL_ERROR = "SPONSORE_APPLY_TRIAL_ERROR"

export const SPONSORE_TRIAL_LISI_SUCCESS = "SPONSORE_TRIAL_LISI_SUCCESS"
export const SPONSORE_TRIAL_LISI_ERROR = "SPONSORE_TRIAL_LISI_ERROR"

export const TRIAL_CLINIC_DASHBOARD_SUCCESS = "TRIAL_CLINIC_DASHBOARD_SUCCESS"
export const TRIAL_CLINIC_DASHBOARD_ERROR = "TRIAL_CLINIC_DASHBOARD_ERROR"

export const TRIAL_APPLICATION_SUCCESS = "TRIAL_APPLICATION_SUCCESS"
export const TRIAL_APPLICATION_ERROR = "TRIAL_APPLICATION_ERROR"

export const TRIAL_APPLICATION_DETAIL_SUCCESS = "TRIAL_APPLICATION_DETAIL_SUCCESS"
export const TRIAL_APPLICATION_DETAIL_ERROR = "TRIAL_APPLICATION_DETAIL_ERROR"

export const TRIAL_APPLICATION_STATUS_SUCCESS = "TRIAL_APPLICATION_STATUS_SUCCESS"
export const TRIAL_APPLICATION_STATUS_ERROR = "TRIAL_APPLICATION_STATUS_ERROR"