export const USERSIGNUP_SUCCESS = "USERSIGNUP_SUCCESS";
export const USERSLOGIN_SUCCESS = "USERSLOGIN_SUCCESS";
export const USERSLOGOUT_SUCCESS = "USERSLOGOUT_SUCCESS";

export const CONTACTFORM_SUCCESS = "CONTACTFORM_SUCCESS";

